---

- name: "copy yearly id script for bahmni Registration ID"
  copy:
    src: idGen.sh
    dest: "/etc/bahmni-installer/idGen.sh"
    owner: "bahmni"
    group: "bahmni"
    mode: 755

- name: "Configure yearly id cronjob"
  cron:
    name: monthly_id_change
    month: "*"
    day: "1"
    minute: "1"
    hour: "0"
    job: "/etc/bahmni-installer/idGen.sh"

